[services]
kerberos = false
hdfsKerberos = false
hdfs = true
hiveMetastore = true

localStackS3 = true
#schemaRegistry = true
#kafka = true

[hiveMetastore]
databaseType = "mysql"
databaseName = "metastore"
databaseUser = "hive"
databasePassword = "hive"
# Optional: use a fixed host port for local database troubleshooting.
#databaseHostPort = 3306
databaseHostPort = 0

[kerberos]
realm = "EXAMPLE.COM"
domain = "example.com"
materialDirectory = "build/bigdata-test/kerberos"
localKrb5ConfPath = "build/bigdata-test/kerberos/krb5.conf"
localClientKeytabPath = "build/bigdata-test/kerberos/app_user.keytab"
debug = true

[hdfs]
dataNodeHostname = "localhost"
localHdfsSitePath = "build/bigdata-test/hadoop/hdfs-site.xml"

[ports]
hdfsNameNode = 8020
hdfsDataNode = 9866
hdfsWeb = 9870
localStackS3 = 4566

[containerLogs]
mode = "STDOUT"
directory = "build/container-logs"
append = false

[containerLogLevels]
kerberos = "DEBUG"
hdfs = "DEBUG"

[containers.localstackS3.env]
DISABLE_CORS_CHECKS = "1"

#[containers.hdfs.env]
#TEST_ENV = "TEST"
