bigdata:
  extensions:
    enabled: true
    config:
      - classpath:spring-bigdata-extensions.toml
  test:
    enabled: true
    ports:
      hdfs-name-node: 8020
      hdfs-data-node: 9866
      hdfs-web: 9870
      s3: 4566
    container-logs:
      mode: stdout
    container-log-levels:
      kerberos: DEBUG
      hdfs: DEBUG
    kerberos:
      enabled: true
      realm: EXAMPLE.COM
      domain: example.com
    hdfs:
      enabled: true
      kerberos-enabled: true
      data-node-hostname: localhost
    s3:
      enabled: true

example:
  s3:
    enabled: true
    bucket: spring-example
    prefix: objects
    create-bucket-on-startup: false
    access-key: test
    secret-key: test
    hadoop:
      fs.defaultFS: hdfs://localhost:8020
      dfs.client.use.datanode.hostname: "true"
      hadoop.security.authentication: kerberos
      dfs.data.transfer.protection: authentication
      fs.s3a.endpoint: http://localhost:4566
      fs.s3a.endpoint.region: us-east-1
      fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
      fs.s3a.path.style.access: "true"
      fs.s3a.connection.ssl.enabled: "false"
      fs.s3a.change.detection.mode: none
      hadoop.tmp.dir: ${user.dir}/build/spring-local/hadoop-tmp
      hadoop.security.credential.provider.path: jceks://hdfs/bigdata-test/spring/s3.jceks
debug: true
